
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[policy.le-stream-derive]
audit-as-crates-io = true

[[exemptions.syn]]
version = "2.0.77"
criteria = "safe-to-deploy"
