
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[policy.le-stream]
audit-as-crates-io = true

[policy."le-stream-derive:1.0.0"]
audit-as-crates-io = true

[[exemptions.hash32]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.heapless]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.intx]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.le-stream]]
version = "3.6.4"
criteria = "safe-to-deploy"

[[exemptions.le-stream-derive]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.macaddr]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.proc-macro2]]
version = "1.0.95"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "2.0.104"
criteria = "safe-to-deploy"
